version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
       - db:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql   
  # api:
  #   container_name: orm-graphql
  #   build:
  #     context: ./
  #     target: production
  #   image: orm-graphql
  #   depends_on:
  #     - db
  #   ports:
  #     - 4000:4000
  #   environment:
  #     NODE_ENV: production
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: postgres
  #   links:
  #     - db
  #   volumes:
  #     - ./:/src
  #     - /src/node_modules

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

volumes:
  db:
    driver: local